#pragma once

// Unreal Engine 4 (4) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "UE4_P_male_postprocessing_animbp_classes.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.DisableDynamics
struct UP_male_postprocessing_animbp_C_DisableDynamics_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_7E493B824BCB2CFCCC4F6AB9BCB8C52A
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_7E493B824BCB2CFCCC4F6AB9BCB8C52A_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_FBF1CE3947118731A2A8269EF1B6EABF
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_FBF1CE3947118731A2A8269EF1B6EABF_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_E27DE33D4D641F303DD72A8BE9F731D0
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_E27DE33D4D641F303DD72A8BE9F731D0_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_41FC9D0041B40C8749BBC89B4C6DC038
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_41FC9D0041B40C8749BBC89B4C6DC038_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_01967D4347E640D1711C94B81EF0A929
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_01967D4347E640D1711C94B81EF0A929_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_461A1FA24E947D587F846C95E9BB81B9
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_461A1FA24E947D587F846C95E9BB81B9_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_FF6057574BBCE789C53A9C9106FDE5D7
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_FF6057574BBCE789C53A9C9106FDE5D7_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_9416FEC44D681EAF065E80B70B19DA08
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_9416FEC44D681EAF065E80B70B19DA08_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_C964500943EBF9690F7D7098B2013E88
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_C964500943EBF9690F7D7098B2013E88_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_BoneDrivenController_E7079335421C1A31C7C22780BD74D4DC
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_BoneDrivenController_E7079335421C1A31C7C22780BD74D4DC_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_5F4B995A4B79FCC7C60E5EB0EE2DB2EF
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_5F4B995A4B79FCC7C60E5EB0EE2DB2EF_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_1CB307314A675FE93FC73BABF84AD83F
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_1CB307314A675FE93FC73BABF84AD83F_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_90823BD7499549AF28D317B259E29DB0
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_90823BD7499549AF28D317B259E29DB0_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_75205F5B44FF3C645262B49FE2A5DF55
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_75205F5B44FF3C645262B49FE2A5DF55_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_C3AD77324DDC34C16C257CA9002EEE2F
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_C3AD77324DDC34C16C257CA9002EEE2F_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_092F499A44E06C908B89909FD0A88F78
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_092F499A44E06C908B89909FD0A88F78_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_BoneDrivenController_9E2D4D4042D893A4E247BA911E48B6A1
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_BoneDrivenController_9E2D4D4042D893A4E247BA911E48B6A1_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_F267CFE54B5108445A8275A31923370D
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_F267CFE54B5108445A8275A31923370D_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_CEE2BCB147998EA3EB857D9616C52DD2
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_CEE2BCB147998EA3EB857D9616C52DD2_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_9CDB568C40D1655B3940368751008585
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_9CDB568C40D1655B3940368751008585_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_F06010BC43122D7FC29F09A340F72ECE
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_F06010BC43122D7FC29F09A340F72ECE_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_EB27D61B4C65F01E96FB48B43158F41E
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_EB27D61B4C65F01E96FB48B43158F41E_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_2B7E2A744CF7EDEA6C699CA43A67DF2F
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_2B7E2A744CF7EDEA6C699CA43A67DF2F_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_E919B0134A93C84C623173AAB7F31784
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_E919B0134A93C84C623173AAB7F31784_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_DF9B8D464D65EAFF8E9784AFC28A1939
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_DF9B8D464D65EAFF8E9784AFC28A1939_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_474230774A85D24C52B353B0D8CF018B
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_474230774A85D24C52B353B0D8CF018B_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_3784B03B48730B1A5D3070B19D1A8713
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_3784B03B48730B1A5D3070B19D1A8713_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_4FA0E88549A11D14E555D2A815F0F695
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_4FA0E88549A11D14E555D2A815F0F695_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_E12DAB504E8F4F3A7612088710D52F22
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_E12DAB504E8F4F3A7612088710D52F22_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_3F4B4B7046392B6A40FA90A94FCF9958
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_3F4B4B7046392B6A40FA90A94FCF9958_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_447334154A90172F3F8665B34F3AA6BD
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_447334154A90172F3F8665B34F3AA6BD_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_ModifyBone_C90495684BA97F0980DE18A0EA7769FC
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_ModifyBone_C90495684BA97F0980DE18A0EA7769FC_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_ModifyBone_080CC1174DA46065556E869E8AB83802
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_ModifyBone_080CC1174DA46065556E869E8AB83802_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_9006B4024CD8E37415329287FF5FE955
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_9006B4024CD8E37415329287FF5FE955_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_805E1F8946FF6C2EC0FE7CA197DFE282
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_805E1F8946FF6C2EC0FE7CA197DFE282_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_F2CC06D64916451825BB71B069D7ACE2
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_F2CC06D64916451825BB71B069D7ACE2_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_7B0A119C441F57425496FEB85FA9F221
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_7B0A119C441F57425496FEB85FA9F221_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_B6C004D64F36D6E66E449E942F98D950
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_B6C004D64F36D6E66E449E942F98D950_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_BDFAE8A84BBA0BF92449028F38FCAA25
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_BDFAE8A84BBA0BF92449028F38FCAA25_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_ECB4544A48DF8459E188F6A9A6375454
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_ECB4544A48DF8459E188F6A9A6375454_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_8FC756824BD6CC0B2C7B4AA20C0BBA5C
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_8FC756824BD6CC0B2C7B4AA20C0BBA5C_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_6691526D442AF563678E539D646CE6DB
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_6691526D442AF563678E539D646CE6DB_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_CD11AD444D1581BC094396BFD1725C00
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_CD11AD444D1581BC094396BFD1725C00_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_A4C849304786734FF2CBB38001609E6E
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_A4C849304786734FF2CBB38001609E6E_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_5EF9CE9342E94FB694478E87C3C7F74C
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_5EF9CE9342E94FB694478E87C3C7F74C_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_4D6DAD0C42C9F2DA8758B6AC002CE915
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_4D6DAD0C42C9F2DA8758B6AC002CE915_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_BB165419434B823609A22DBA230B8D2D
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_BB165419434B823609A22DBA230B8D2D_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_16CEB6F54AC181C52BE95088A503646C
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_16CEB6F54AC181C52BE95088A503646C_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_BlendListByBool_F1FB8086446FA71D0349EEAD4DB7BEC4
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_BlendListByBool_F1FB8086446FA71D0349EEAD4DB7BEC4_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_A88DBED842B20BD4EB7B26AE3E56C09B
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_A88DBED842B20BD4EB7B26AE3E56C09B_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_968F22FF4E3BB56D80E75D975F6F4AB6
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_968F22FF4E3BB56D80E75D975F6F4AB6_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_E6F24E9F42D8F4CA39DFEF8DD4B476D6
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_E6F24E9F42D8F4CA39DFEF8DD4B476D6_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_8F07458844A2E56A1C5762AF8D421F55
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_8F07458844A2E56A1C5762AF8D421F55_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_B448C00C4B81425AA0595CBEB708EF34
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_B448C00C4B81425AA0595CBEB708EF34_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_34E33F904DED201397E5E0982242FAB0
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_34E33F904DED201397E5E0982242FAB0_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_34CDE44947600378D8934E969F58DB3D
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_34CDE44947600378D8934E969F58DB3D_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_967427C845107214E25B858D419F9346
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_967427C845107214E25B858D419F9346_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_307FDBCD4F6EB7450D89A8B385EC8495
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_307FDBCD4F6EB7450D89A8B385EC8495_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_360C4C7B48FD61F1218E299776C618F6
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_360C4C7B48FD61F1218E299776C618F6_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_B97A99F54B9C36B8591BF881A2CC855D
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_B97A99F54B9C36B8591BF881A2CC855D_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_799FF08C4AE6A02392134BA990555C5A
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_799FF08C4AE6A02392134BA990555C5A_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_A3343E5146407BF1153478B18226CBF5
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_A3343E5146407BF1153478B18226CBF5_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_D724444E450F207DCCF56BA0924D1BDD
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_D724444E450F207DCCF56BA0924D1BDD_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_31A733DD44B66B19227A9DB473422B74
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_31A733DD44B66B19227A9DB473422B74_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_FBF213AE471310127AD48E8FCFDFB8A6
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_FBF213AE471310127AD48E8FCFDFB8A6_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_A75B97414077C2E80D2B7CA024A90A5A
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_A75B97414077C2E80D2B7CA024A90A5A_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_DC1D6E84429A24E4F81C51982DC36757
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_DC1D6E84429A24E4F81C51982DC36757_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.BlueprintUpdateAnimation
struct UP_male_postprocessing_animbp_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_6B95FABA4BECC18AD5B72E8A74BC0D43
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_6B95FABA4BECC18AD5B72E8A74BC0D43_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_0BDBFA2849868DF53DB2518174CD4C79
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_0BDBFA2849868DF53DB2518174CD4C79_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.SetSecondaryMotion
struct UP_male_postprocessing_animbp_C_SetSecondaryMotion_Params
{
	float                                              SkirtHeavyAlpha;                                          // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
	float                                              SkirtLightAlpha;                                          // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
	float                                              TabardAdjustAlpha;                                        // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.UpdateAimOffsetTarget
struct UP_male_postprocessing_animbp_C_UpdateAimOffsetTarget_Params
{
	struct FVector                                     Target;                                                   // (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData)
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EnableAimOffset
struct UP_male_postprocessing_animbp_C_EnableAimOffset_Params
{
	bool                                               Enable;                                                   // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.SetCBladePullAimRotation
struct UP_male_postprocessing_animbp_C_SetCBladePullAimRotation_Params
{
	struct FRotator                                    Rotation;                                                 // (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData)
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_999F20F64527328C94A834A6F38A62E1
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_999F20F64527328C94A834A6F38A62E1_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.SetCBladePullAimTarget
struct UP_male_postprocessing_animbp_C_SetCBladePullAimTarget_Params
{
	class UPrimitiveComponent*                         AimTarget;                                                // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.SetCBladeEnablePullAim
struct UP_male_postprocessing_animbp_C_SetCBladeEnablePullAim_Params
{
	bool                                               Enable;                                                   // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.SetCBladePullAttachTarget
struct UP_male_postprocessing_animbp_C_SetCBladePullAttachTarget_Params
{
	class UPrimitiveComponent*                         AttachTarget;                                             // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
	struct FVector                                     ImpactPoint;                                              // (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData)
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.SetIsClient
struct UP_male_postprocessing_animbp_C_SetIsClient_Params
{
	bool                                               IsClient;                                                 // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_C70EA47147E6C24B8D3455AE9884AE0D
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_AnimDynamics_C70EA47147E6C24B8D3455AE9884AE0D_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.SetWeaponOnBack
struct UP_male_postprocessing_animbp_C_SetWeaponOnBack_Params
{
	bool                                               OnBack;                                                   // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_ModifyBone_239992334BFBEE8B61BE39AC37B34E19
struct UP_male_postprocessing_animbp_C_EvaluateGraphExposedInputs_ExecuteUbergraph_P_male_postprocessing_animbp_AnimGraphNode_ModifyBone_239992334BFBEE8B61BE39AC37B34E19_Params
{
};

// Function P_male_postprocessing_animbp.P_male_postprocessing_animbp_C.ExecuteUbergraph_P_male_postprocessing_animbp
struct UP_male_postprocessing_animbp_C_ExecuteUbergraph_P_male_postprocessing_animbp_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
